name: Inter Coach
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: resumeId
    value: ''
  - key: analysisId
    value: ''
  - key: authToken
    value: ''
  - key: refreshToken
    value: ''
  - key: userId
    value: ''
