name: Inter Coach
values:
  - key: baseUrl
    value: "http://localhost:3000"
    enabled: true
  - key: authToken
    value: ""
    enabled: true
  - key: refreshToken
    value: ""
    enabled: true
  - key: resumeId
    value: ""
    enabled: true
  - key: analysisId
    value: ""
    enabled: true
